apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: elyra-demo-dspa
  namespace: elyra-demo-project
spec:
  dspVersion: v2
  objectStorage:
    minio:
      deploy: true
      bucket: "mlpipeline"
      image: "quay.io/minio/minio:RELEASE.2023-05-18T00-05-36Z"
      s3CredentialsSecret:
        accessKey: "accesskey"
        secretKey: "secretkey" #notsecret
        secretName: "mlpipeline-minio-artifact"
---
apiVersion: v1
kind: Namespace
metadata:
  name: elyra-demo-project
  labels:
    opendatahub.io/dashboard: "true"
    modelmesh-enabled: "true"
    name: elyra-demo-project
  annotations:
    openshift.io/description: "Elyra MLOps Demo Project"
    openshift.io/display-name: "Elyra Demo"
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: elyra-demo-project
type: Opaque
data:
  password: bWxwaXBlbGluZQ==  #notsecret
---
apiVersion: v1
kind: Secret
metadata:
  name: mlpipeline-minio-artifact
  namespace: elyra-demo-project
type: Opaque
data:
  accesskey: bWluaW8=      #notsecret
  secretkey: bWluaW8xMjM=  #notsecret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elyra-demo-admin
  namespace: elyra-demo-project
subjects:
- kind: User
  name: demo-user
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: pipeline-runner
  namespace: elyra-demo-project
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-runner
  namespace: elyra-demo-project
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: elyra-runtime
  namespace: elyra-demo-project
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/modh/runtime-images:runtime-datascience-ubi9-python-3.9-2023c
    importPolicy:
      scheduled: true
  - name: tensorflow
    from:
      kind: DockerImage
      name: quay.io/modh/runtime-images:runtime-tensorflow-ubi9-python-3.9-2023c
    importPolicy:
      scheduled: true
  - name: pytorch
    from:
      kind: DockerImage
      name: quay.io/modh/runtime-images:runtime-pytorch-ubi9-python-3.9-2023c
    importPolicy:
      scheduled: true
